:defaults: &defaults
  :app_name: Dreamail
  :app_domain: dreamail.com
  :app_site: http://dreamail.com
  
  :juggernaut_host: localhost:8080
  
  :aws:
    :access_key_id: replaceme
    :secret_access_key: replaceme
    :bucket: dreamail-production

:development:
  <<: *defaults
  
  :app_domain: localhost
  :app_site: http://localhost:3000
  
:test:
  <<: *defaults

:staging:
  <<: *defaults
    
:production:
  <<: *defaults
    
  :juggernaut_host: dreamail.com:8080